apiVersion: apps/v1
kind: Deployment
metadata:
  name: lokesh-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lokesh-portfolio
  template:
    metadata:
      labels:
        app: lokesh-portfolio
    spec:
      containers:
      - name: lokesh-portfolio
        image: lokeshportfolioacr.azurecr.io/lokesh-portfolio:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lokesh-portfolio-service
spec:
  selector:
    app: lokesh-portfolio
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
